#!/bin/bash
outputDir="$HOME/tmp/downloadImage/image/"
echo "downloading image to $outputDir"
mkdir -p $outputDir
while IFS='' read -r line || [[ -n "$line" ]]; do
    #echo "Text read from file: $line"
    wget -P $outputDir $line
done < /tmp/images
#done < "$1"
